services:
    node:
       restart: always
       image: camaralab/db_server:nodedbarm
       ports:
        - "8080:8080"
       depends_on:
        - redis
    flask:
       restart: always
       image: camaralab/db_server:flaskdbarm
       ports:
        - "5000:5000"
       volumes:
        - /home/ubuntu/mysql_files:/app/config
    redis:
       restart: always
       image: camaralab/db_server:redisdbarm
       ports:
        - "6379:6379"
    nginx:
       restart: always
       image: camaralab/db_server:nginxdbarm
       ports:
        - "80:80"
       depends_on:
        - node
