version: "3.8"
services:
    node:
        restart: always
        build:
            context: ./node-api
        ports:
            - "8080:8080"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
    flask:
        restart: always
        build:
          context: ./flask-api
        ports:
            - "5000:5000"
